site_name: Earthcube Infrastructure Documentation
#theme: 'material'
#theme: 'mkdocs'
theme: 'readthedocs'
plugins:
  - search
# literate_nav must load after multirepo for the features to be available.
  - multirepo:
      # (optional) tells multirepo to cleanup the temporary directory after site is built.
      cleanup: true
  - literate-nav
  # get a NoneType error, even when trying to generate in Geocodes-Metadata
#  - schema_reader:
#      include:
#        - "./docs/GeoCODES-Metadata/schemas/"
nav:
  - Home: index.md
  - Developers: '/developers/'
  - Geocodes: '!import https://github.com/earthcube/geocodes?branch=doctest&docs_dir=docs&config=mkdocs.yml'
  - Metadata: '!import https://github.com/earthcube/GeoCODES-Metadata?branch=main'
  - Indexing:
    - Gleaner: '!import https://github.com/gleanerio/gleaner?branch=dev_docs'
    - Nabu: '!import https://github.com/gleanerio/nabu?branch=dev_docs'
  - User Interface:
      - Facetsearch: "https://github.com/earthcube/facetsearch"
