site_name: Earthcube Infrastructure Documentation
#theme: 'material'
#theme: 'mkdocs'
theme:
  name: material
#  name: 'readthedocs'
  features:
    #    - content.code.copy
    - navigation.sections
markdown_extensions:
  - toc:
      permalink: 
  - attr_list
  - def_list
  - tables
  - pymdownx.highlight:
      use_pygments: false
  - admonition
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
# literate_nav must load after multirepo for the features to be available.
  - multirepo:
      # (optional) tells multirepo to cleanup the temporary directory after site is built.
      cleanup: true
  -  mermaid2
  - literate-nav
  -  mkdocs-jupyter
  - callouts
  # get a NoneType error, even when trying to generate in Geocodes-Metadata
#  - schema_reader:
#      include:
#        - "./docs/GeoCODES-Metadata/schemas/"
nav:
  - Home: index.md
  - Examples:
      - Geocodes: 'examples/geocodes.md'
      - Developement: 'examples/developement/'
      - Community: 'examples/community/'
  - Science On Schema:  '!import https://github.com/earthcube/GeoCODES-Metadata?branch=main'
  - Earthcube Utilities:
      - Utilities: "https://earthcube.github.io/earthcube_utilities/"
 #     - Notebook Proxy: '!import https://github.com/earthcube/earthcube_utilities.git?branch=dev&docs_dir=notebook_proxy/&config=notebook_proxy/mkdocs.yml'
  - User Interface:
      - Facetsearch:
          - UI: "https://geocodes.earthcube.org/#/landing"
          - repository: "https://github.com/earthcube/facetsearch"
  - Resource Management:
      - JSONLD Forms:
          - UI: "https://addto.earthcube.org"
          - repository: "https://github.com/earthcube/jsonld_forms"
  - Indexing:
#      - Gleaner: '!import https://github.com/gleanerio/gleaner?branch=dev_docs'
#      - Nabu: '!import https://github.com/gleanerio/nabu?branch=dev_docs'
      - Gleaner Docs: '!import https://github.com/gleanerio/gleanerdocs.github.io?branch=docs_mkdocs&config=mkdocs_ec.yml'
      - Summarization: '!import https://github.com/earthcube/earthcube_utilities.git?branch=dev&docs_dir=summarize/docs&config=summarize/mkdocs.yml'
  - Developers:
      - General Developer Information: 'developers/'
      - Services Infrastructure: '!import https://github.com/earthcube/geocodes?branch=main&docs_dir=docs&config=mkdocs.yml'
      - Ingest Orchestration: '!import https://github.com/gleanerio/scheduler.git?branch=dev'
 #     - Integration Testing: '!import https://github.com/earthcube/GeoCODES-Metadata.git?branch=main&docs_dir=integrationtesting/docs&config=integrationtesting/mkdocs.yml'
      - Repositories: "https://github.com/earthcube"
