site_name: Geocodes Documentation
#theme: 'material'
#theme: 'mkdocs'
theme: 'readthedocs'
plugins:
  - search
  - multirepo:
      # (optional) tells multirepo to cleanup the temporary directory after site is built.
      cleanup: true
      repos:
        - section: Geocodes
          # you can define the edit uri path
          import_url: 'https://github.com/earthcube/geocodes'
        - section: Metadata
          import_url: 'https://github.com/earthcube/GeoCODES-Metadata'
        - section: Gleaner
          import_url: 'https://github.com/gleanerio/gleaner'
        - section: Nabu
          import_url: 'https://github.com/gleanerio/nabu'
  # get a NoneType error, even when trying to generate in Geocodes-Metadata
#  - schema_reader:
#      include:
#        - "./docs/GeoCODES-Metadata/schemas/"
