name: mkdocs
on:
  push:
    branches:
      - main
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
# no cleaup needed
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: earthcube/geocodes
          path: docs/geocodes
      - run: cd docs/geocodes && rm -rf "!(docs)" && cd ..
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs
 #     - run: cd docs/ && mkdocs gh-deploy --force --clean --verbose
      - run:  mkdocs gh-deploy --force --clean --verbose

